parameters:
    contact.template:   MailerBundle::contactMail.html.twig
    contact.subject:    mailing.contact.subject

services:
    mailer.contact:
        class:  Dende\MailerBundle\Service\Mailer
        arguments: [@mailer]
        calls:
            - [ setTranslator, ["@translator"]]
            - [ setTemplating, ["@templating"]]
            - [ setSubject,['%contact.subject%']]
            - [ setTemplate,['%contact.template%']]
            - [ setTo,['some@email.com']]
            