parameters:
    testing_url: test.gyman.pl

imports:
    - { resource: config_dev.yml }

framework:
    translator:      false
    test:            true
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

front:
    testing_url: %testing_url%
    
doctrine:
    dbal:
        user:     test
        password: test.123