services:
    subscription_bundle.registered_user_subscriber:
        class: Dende\SubscriptionBundle\Service\Subscriber\RegisteredUserSubscriber
        calls:
            - [setEntityManager,["@doctrine.orm.entity_manager"]]
            - [setSession,["@session"]]
            - [setSubscriptionFactory,["@subscription_bundle.subscription_factory"]]
        tags:
            - { name: kernel.event_subscriber }
            
    subscription_bundle.subscription_factory:
        class: Dende\SubscriptionBundle\Entity\SubscriptionFactory
        
