<?php

namespace Dende\SubscriptionBundle\Factory;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-02 at 02:31:14.
 */
class SubscriptionFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SubscriptionFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SubscriptionFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Dende\SubscriptionBundle\Entity\SubscriptionFactory::createSubscription
     * @todo   Implement testCreateSubscription().
     */
    public function testCreateSubscription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
